# Generated by Django 5.2.8 on 2025-11-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this webhook', max_length=255)),
                ('url', models.URLField(help_text='URL to send webhook payloads to')),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted'), ('import.started', 'Import Started'), ('import.completed', 'Import Completed'), ('import.failed', 'Import Failed')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('secret_key', models.CharField(blank=True, help_text='Optional secret for signing webhooks (HMAC)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'is_active'], name='webhooks_we_event_t_40f4e2_idx'), models.Index(fields=['is_active'], name='webhooks_we_is_acti_683202_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('is_success', models.BooleanField(default=False)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='webhooks.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook', 'created_at'], name='webhooks_we_webhook_981dcb_idx'), models.Index(fields=['is_success', 'created_at'], name='webhooks_we_is_succ_567d59_idx')],
            },
        ),
    ]
