# Generated by Django 5.2.8 on 2025-11-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportBatch',
        ),
    ]
